version: "3.9"

services:
  api:
    build:
      dockerfile: .docker/dev/Dockerfile
      context: .
    privileged: true
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0
    volumes:
      - postgresql:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=quanttrade_api
      - POSTGRES_PASSWORD=superdupersecret
      - POSTGRES_DB=quanttrade_api_dev

volumes:
  postgresql:
